# Generated by Django 4.1.4 on 2022-12-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Счет фактрура', 'verbose_name_plural': 'Счет фактрура'},
        ),
        migrations.AlterModelOptions(
            name='productinvoice',
            options={'verbose_name': 'Фактура', 'verbose_name_plural': 'Фактура'},
        ),
        migrations.RemoveField(
            model_name='productinvoice',
            name='address',
        ),
        migrations.RemoveField(
            model_name='productinvoice',
            name='passport_seria',
        ),
        migrations.AddField(
            model_name='invoice',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='passport_seria',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Паспорт (серия)'),
        ),
    ]
