# Generated by Django 4.1.4 on 2023-01-18 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_product_price_productinvoice_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
