# Generated by Django 4.1.4 on 2023-01-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Наименование - EN'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Наименование - RU'),
        ),
    ]
